from pathlib import Path
from PIL import Image, ImageOps
from collections import deque
import hashlib, json
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'assets/reference-scene'

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def cut_background(im):
    im = im.convert('RGBA')
    w, h = im.size
    pixels = im.load()
    visited = set()
    queue = deque([(x, y) for x in range(w) for y in (0, h-1)])
    queue.extend([(x, y) for x in (0, w-1) for y in range(h)])
    while queue:
        x, y = queue.popleft()
        if (x, y) in visited or not (0 <= x < w and 0 <= y < h):
            continue
        visited.add((x, y))
        r, g, b, a = pixels[x, y]
        if min(r,g,b) < 204 or max(r,g,b)-min(r,g,b) > 46:
            continue
        pixels[x, y] = (r, g, b, 0)
        queue.extend([(x-1,y), (x+1,y), (x,y-1), (x,y+1)])
    return im

def pixel(im, colors=64):
    alpha = im.getchannel('A') if im.mode == 'RGBA' else None
    result = im.convert('RGB').quantize(colors=colors,dither=Image.Dither.NONE).convert('RGB')
    if alpha:
        result.putalpha(alpha.point(lambda value:255 if value>127 else 0))
    return result

def periodic(im):
    im=im.convert('RGB'); p=im.load(); w,h=im.size
    for x in range(w):
        avg=tuple((p[x,0][k]+p[x,h-1][k])//2 for k in range(3))
        p[x,0]=p[x,h-1]=avg
    for y in range(h):
        avg=tuple((p[0,y][k]+p[w-1,y][k])//2 for k in range(3))
        p[0,y]=p[w-1,y]=avg
    return im

def save(im, relative):
    path=OUT/relative
    path.parent.mkdir(parents=True,exist_ok=True)
    im.save(path)
    sprite=relative.startswith('sprites/')
    config='[remap]\nimporter="texture"\ntype="CompressedTexture2D"\n[deps]\nsource_file="res://assets/reference-scene/'+relative+'"\n[params]\ncompress/mode=0\nmipmaps/generate='+('false' if sprite else 'true')+'\nprocess/fix_alpha_border=true\ndetect_3d/compress_to=0\n'
    path.with_suffix(path.suffix+'.import').write_text(config)
    return {'path':path.relative_to(ROOT).as_posix(),'size':list(im.size),'sha256':digest(path),'mode':im.mode}

def main():
    spec=json.loads((ROOT/'art_source/reference-scene/manifests/intake.json').read_text())
    source=ROOT/spec['intake']['path']
    assert digest(source)==spec['intake']['sha256']
    sheet=Image.open(source).convert('RGB'); cells={}; entries=[]
    for item in spec['items']:
        x,y,w,h=item['cell']
        tile=sheet.crop((x,y,x+w,y+h)); cells[item['id']]=tile
        if item['kind']=='texture':
            entries.append(save(periodic(pixel(tile)), 'textures/'+item['id']+'.png'))
        elif item['kind']=='decal':
            entries.append(save(pixel(cut_background(tile)), 'textures/'+item['id']+'.png'))
    awning=Image.new('RGB',(64,64)); p=awning.load()
    for y in range(64):
        for x in range(64):
            p[x,y]=cells['green' if x//8%2==0 else 'canvas'].getpixel((x,y))
    entries.append(save(periodic(pixel(awning)), 'textures/awning_green.png'))
    for name in ['hero','merchant','keeper','baker','noble']:
        directions=['hero_front','hero_back','hero_side','hero_side'] if name=='hero' else [name+'_front']*4
        atlas=Image.new('RGBA',(192,256))
        for row,key in enumerate(directions):
            part=cut_background(cells[key]); part=part.crop(part.getbbox())
            part.thumbnail((42,58),Image.Resampling.NEAREST)
            if row==2: part=ImageOps.mirror(part)
            frame=Image.new('RGBA',(48,64))
            frame.alpha_composite(part,((48-part.width)//2,62-part.height))
            frame=pixel(frame,48)
            for column in range(4):
                pose=frame.copy()
                if name=='hero' and column in (1,3):
                    # Limited derived walk. These poses were not generated by AI.
                    left=frame.crop((10,52,24,62))
                    right=frame.crop((24,52,38,62))
                    pose.paste((0,0,0,0),(9,52,39,62))
                    pose.alpha_composite(left,(9 if column==1 else 11,52))
                    pose.alpha_composite(right,(25 if column==1 else 23,52))
                atlas.alpha_composite(pose,(column*48,row*64))
        entries.append(save(atlas,'sprites/'+name+'.png'))
    result={'schema':1,'source_type':'imagegen-derived','input_sha256':digest(source),
            'generator':'tools/p9/process_assets.py','sprite_frame':[48,64],
            'directions':['front','back','left','right'],
            'animation_note':'Hero has three sourced directions plus mirroring and derived lower-leg swing. NPCs are front-only static sprites repeated in atlas for API compatibility.',
            'assets':entries}
    (ROOT/'art_source/reference-scene/manifests/processed.json').write_text(json.dumps(result,indent=2)+'\n')
    print('P9_PIXEL_ASSETS',len(entries))

if __name__=='__main__':
    main()
